"""add_daifong_ext_fields

Revision ID: 1deb28fa4000
Revises: 32c32fa223b2
Create Date: 2026-07-20 12:15:17.519204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1deb28fa4000'
down_revision: Union[str, None] = '32c32fa223b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('booking_source', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('id_number', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('dropoff_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('assigned_plate', sa.String(length=15), nullable=True))
    op.add_column('orders', sa.Column('driver_name', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('operator', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'operator')
    op.drop_column('orders', 'driver_name')
    op.drop_column('orders', 'assigned_plate')
    op.drop_column('orders', 'dropoff_time')
    op.drop_column('orders', 'id_number')
    op.drop_column('orders', 'booking_source')
    # ### end Alembic commands ###
