"""expand passenger_phone to 100

Revision ID: 32c32fa223b2
Revises: a8de23dffa23
Create Date: 2026-07-10 09:05:16.302210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32c32fa223b2'
down_revision: Union[str, None] = 'a8de23dffa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'passenger_phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'passenger_phone',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
