"""expand_eligibility

Revision ID: 78f39fba5c81
Revises: 513443f1d738
Create Date: 2026-07-20 12:26:01.162508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78f39fba5c81'
down_revision: Union[str, None] = '513443f1d738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'eligibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'eligibility',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
