"""expand subsidy_balance to 100

Revision ID: a8de23dffa23
Revises: 0036
Create Date: 2026-07-10 09:03:08.884857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8de23dffa23'
down_revision: Union[str, None] = '0036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'subsidy_balance',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'subsidy_balance',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
